// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOEyrqWYfCEyrQX4mPn6iyn_X73LtYTjU',
    appId: '1:1028602204349:web:914825ec11e746632467d4',
    messagingSenderId: '1028602204349',
    projectId: 'my-firebase-project-f8ab3',
    authDomain: 'my-firebase-project-f8ab3.firebaseapp.com',
    databaseURL: 'https://my-firebase-project-f8ab3-default-rtdb.firebaseio.com',
    storageBucket: 'my-firebase-project-f8ab3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA18sc-XPPkec7bLcmYy_WPLL-e233hIcg',
    appId: '1:1028602204349:android:4e2013f27547d8612467d4',
    messagingSenderId: '1028602204349',
    projectId: 'my-firebase-project-f8ab3',
    databaseURL: 'https://my-firebase-project-f8ab3-default-rtdb.firebaseio.com',
    storageBucket: 'my-firebase-project-f8ab3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnTea4ZKfMS0tpsgxOJ8POIHnK091RESY',
    appId: '1:1028602204349:ios:ab98fd83603a4c542467d4',
    messagingSenderId: '1028602204349',
    projectId: 'my-firebase-project-f8ab3',
    databaseURL: 'https://my-firebase-project-f8ab3-default-rtdb.firebaseio.com',
    storageBucket: 'my-firebase-project-f8ab3.appspot.com',
    iosClientId: '1028602204349-n16h3r5f1gn4su9e46p9rflvfv7vb7ra.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirebaseproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnTea4ZKfMS0tpsgxOJ8POIHnK091RESY',
    appId: '1:1028602204349:ios:ab98fd83603a4c542467d4',
    messagingSenderId: '1028602204349',
    projectId: 'my-firebase-project-f8ab3',
    databaseURL: 'https://my-firebase-project-f8ab3-default-rtdb.firebaseio.com',
    storageBucket: 'my-firebase-project-f8ab3.appspot.com',
    iosClientId: '1028602204349-n16h3r5f1gn4su9e46p9rflvfv7vb7ra.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirebaseproject',
  );
}
